### ISSUE TITLE
Help button requires ST-GUIDE

### ISSUE THREAD

**Issue by xdelatour** [freemint/toswin2#1]
Hi,
Please excuse my bad English.

The "Help" button works successfully only if ST-GUIDE is already running. 
In other case, the 'call_stguide' function (in av.c) fails and displays an error.

I reused some lines of codes from hyp_view (dl_help.c:STGuideHelp) to get the value of HELPVIEWER and launch it if not running (see attached diff file).
[av.c.patch.txt](https://github.com/freemint/toswin2/files/6960560/av.c.patch.txt)

Note:
HELPVIEWER must be added to xaaes.cnf (for example, setenv HELPVIEWER c:\usr\GEM\hypview\hyp_view.app)
Under ARANyM, if hostfs is case-sensitive, hyp_view can't read its config file unless the file extension is uppercase (.CFG)

Config: ARAnyM+bootable freemint snapshot

**Comment by th-otto** [comment]
Could you please attach a context diff (diff -u) instead of a normal diff?

**Comment by xdelatour** [comment]
yes : 
[av.c.patch.txt](https://github.com/freemint/toswin2/files/6961888/av.c.patch.txt)

**Comment by th-otto** [comment]
Oops. Almost forgot about this, sorry. Should be fixed now.
